<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PollR.AspNetCore</RootNamespace>
    <!-- Nuget -->
    <IsPackable>True</IsPackable>
    <PackageId>PollR.AspNetCore</PackageId>
    <Description>A polling library for ASP.NET to SSE streams.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\PollR\PollR.csproj" />
  </ItemGroup>
</Project>
