<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PollR</RootNamespace>
    <!-- Nuget -->
    <IsPackable>True</IsPackable>
    <PackageId>PollR</PackageId>
    <Description>A polling library for .NET.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ZLinq" Version="1.5.6" />
  </ItemGroup>
</Project>
