<Project>
  <PropertyGroup>
    <!-- Nuget Configuration -->
    <Authors>@chrlschn</Authors>
    <Company />
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/CharlieDigital/PollR</RepositoryUrl>
    <PackageProjectUrl>https://github.com/CharlieDigital/PollR</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/CharlieDigital/PollR/releases</PackageReleaseNotes>
    <PackageTags>polling; sse; .net; streams</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <SignAssembly>False</SignAssembly>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.0</FileVersion>
    <Version>1.1.0</Version>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
